name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Update data.json
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: |
        npm ci
        node index.js
      env:
        CI: true
    - name: Commit files
    - run: |
        git config --local user.email "bernard.adhitya@gmail.com"
        git config --local user.name "bernardadhitya"
        git commit -m "[System] Auto-update data.json" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
